/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author EarthKing
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    public static String email2;
    public RegistrationForm() {
        initComponents();
      
        
       this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
       otp_label.setVisible(false);
       otptxt.setVisible(false);
       otp_seprator.setVisible(false);
       verify_email.setVisible(false);
       
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(100, new Color(204, 204, 204));
        jPanel2 = new RoundedPanel(100, new Color(67, 173, 221));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        otptxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passtxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        verify_email = new javax.swing.JLabel();
        mobtxt = new javax.swing.JTextField();
        otp_seprator = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        usertxt = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        MobileLabel = new javax.swing.JLabel();
        otp_label = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(67, 173, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 520));

        jPanel3.setBackground(new java.awt.Color(4, 34, 120));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(4, 34, 120));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 20));

        otptxt.setBackground(new java.awt.Color(4, 34, 120));
        otptxt.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        otptxt.setForeground(new java.awt.Color(255, 255, 255));
        otptxt.setBorder(null);
        otptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otptxtMouseClicked(evt);
            }
        });
        otptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otptxtActionPerformed(evt);
            }
        });
        otptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otptxtKeyPressed(evt);
            }
        });
        jPanel3.add(otptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 230, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 230, 10));

        passtxt.setBackground(new java.awt.Color(4, 34, 120));
        passtxt.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        passtxt.setForeground(new java.awt.Color(255, 255, 255));
        passtxt.setBorder(null);
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        jPanel3.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 10));

        verify_email.setBackground(new java.awt.Color(4, 34, 120));
        verify_email.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        verify_email.setForeground(new java.awt.Color(255, 255, 255));
        verify_email.setText("Verify Email");
        verify_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verify_emailMouseClicked(evt);
            }
        });
        jPanel3.add(verify_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 20));

        mobtxt.setBackground(new java.awt.Color(4, 34, 120));
        mobtxt.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        mobtxt.setForeground(new java.awt.Color(255, 255, 255));
        mobtxt.setBorder(null);
        jPanel3.add(mobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 30));
        jPanel3.add(otp_seprator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 108, 230, -1));

        usertxt.setBackground(new java.awt.Color(4, 34, 120));
        usertxt.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        usertxt.setForeground(new java.awt.Color(255, 255, 255));
        usertxt.setBorder(null);
        usertxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usertxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usertxtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usertxtMouseReleased(evt);
            }
        });
        jPanel3.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 30));

        EmailLabel.setBackground(new java.awt.Color(4, 34, 120));
        EmailLabel.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Username");
        EmailLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailLabelMouseEntered(evt);
            }
        });
        jPanel3.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 20));

        MobileLabel.setBackground(new java.awt.Color(4, 34, 120));
        MobileLabel.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        MobileLabel.setForeground(new java.awt.Color(255, 255, 255));
        MobileLabel.setText("Contact No.");
        jPanel3.add(MobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 20));

        otp_label.setBackground(new java.awt.Color(4, 34, 120));
        otp_label.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        otp_label.setForeground(new java.awt.Color(255, 255, 255));
        otp_label.setText("OTP");
        jPanel3.add(otp_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 80, 20));

        emailtxt.setBackground(new java.awt.Color(4, 34, 120));
        emailtxt.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(255, 255, 255));
        emailtxt.setBorder(null);
        emailtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailtxtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailtxtMouseReleased(evt);
            }
        });
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        emailtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailtxtKeyReleased(evt);
            }
        });
        jPanel3.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 230, 30));

        jLabel7.setBackground(new java.awt.Color(4, 34, 120));
        jLabel7.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 80, 20));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 10));

        jButton3.setBackground(new java.awt.Color(4, 34, 120));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Register");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, 40));

        jButton4.setBackground(new java.awt.Color(4, 34, 120));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 410, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void otptxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otptxtMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_otptxtMouseClicked

    private void otptxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otptxtKeyPressed
        // TODO add your handling code here:
        verify_email.setEnabled(true);
       
    }//GEN-LAST:event_otptxtKeyPressed

    private void otptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otptxtActionPerformed

    private void emailtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailtxtMouseClicked
        // TODO add your handling code here:
        verify_email.setEnabled(true);
    }//GEN-LAST:event_emailtxtMouseClicked

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void emailtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtxtKeyPressed
        // TODO add your handling code here:
        verify_email.setVisible(true);
    }//GEN-LAST:event_emailtxtKeyPressed

    private void verify_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verify_emailMouseClicked
        // TODO add your handling code here:
         otp_label.setVisible(true);
       otptxt.setVisible(true);
       otp_seprator.setVisible(true);
       
       
       mail.sendmail();
        
    }//GEN-LAST:event_verify_emailMouseClicked

    private void emailtxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailtxtMouseReleased
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_emailtxtMouseReleased

    private void emailtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtxtKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailtxtKeyReleased

    private void EmailLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailLabelMouseEntered
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_EmailLabelMouseEntered

    private void usertxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_usertxtMouseEntered

    private void usertxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_usertxtMouseReleased

    private void usertxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMouseExited
        // TODO add your handling code here:
         
    }//GEN-LAST:event_usertxtMouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        try{  
    String myDriver = "org.gjt.mm.mysql.Driver";
     String myUrl = "jdbc:mysql://localhost:3306/myproject?autoReconnect=true&useSSL=false";
     
     Class.forName(myDriver);
      Connection con = DriverManager.getConnection(myUrl,"root",""); 
    Statement st = con.createStatement();
     Statement st2 = con.createStatement();   
        
         
        
        String usname = usertxt.getText();
        String pass = passtxt.getText();
        String mobile = mobtxt.getText();
         String email = emailtxt.getText();
         Get.senderemail = email;
       
        
        
        


     if (usname.length()>0 && pass.length()>0 && otptxt.getText().equals(tryotp.pk) )
      {
    
    
    String query = "insert into data(username,password,mobile,email) values ('"+usname+"','"+pass+"',"+mobile+",'"+email+"')";;
    
    String query2 = "insert into admin values('"+usname+"','"+pass+"')";
    
    st.executeUpdate(query);
    st2.executeUpdate(query2);
     
      
      

   
       con.close();
       this.dispose();
       LoginForm a = new LoginForm();
       a.setVisible(true);
       
       
    }
   else 
   {
       
       usertxt.setText("");
       passtxt.setText("");
       mobtxt.setText("");
       emailtxt.setText("");
       otptxt.setText("");
       JOptionPane.showMessageDialog(null,"something went wrong.Try again ! ");
   }


        
         
     
         
         
         
     
    
    
    
}
        
         

        catch(Exception e)
        {
            System.out.print(e);
        }

        
                                          
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel MobileLabel;
    public static javax.swing.JTextField emailtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField mobtxt;
    private javax.swing.JLabel otp_label;
    private javax.swing.JSeparator otp_seprator;
    private javax.swing.JTextField otptxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel verify_email;
    // End of variables declaration//GEN-END:variables

 class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//            
        }
    }




}
